const PLANNED_OUTPUT_DETAILS=12000;
const state={prostoi:[],brak:[],filteredP:[],filteredB:[],charts:{}};
const $=id=>document.getElementById(id);
const norm=s=>String(s??'').replace(/^\uFEFF/,'').trim();
const num=v=>Number(String(v??0).replace(',','.'))||0;
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"'){q=!q}else if(c===';'&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x!==''))rows.push(row);const h=rows.shift().map(norm);return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,norm(r[i])])))}
async function loadDefaults(){const [p,b]=await Promise.all([fetch('clean_01_prostoi.csv').then(r=>r.text()),fetch('clean_02_brak.xlsx').then(r=>r.arrayBuffer())]);state.prostoi=parseCsv(p);state.brak=parseXlsx(b);afterLoad('Загружены файлы проекта')}
function parseXlsx(buf){const wb=XLSX.read(buf,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}).map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[norm(k),v instanceof Date?v.toISOString().slice(0,10):norm(v)])))}
async function loadUser(){const pf=$('prostoiFile').files[0],bf=$('brakFile').files[0];if(pf)state.prostoi=parseCsv(await pf.text());if(bf)state.brak=parseXlsx(await bf.arrayBuffer());afterLoad('Данные загружены пользователем')}
function afterLoad(msg){$('loadStatus').textContent=msg;const dates=[...state.prostoi.map(r=>r['Дата']),...state.brak.map(r=>r['Дата контроля'])].sort();$('dateFrom').value=dates[0]||'';$('dateTo').value=dates.at(-1)||'';const shops=[...new Set(state.prostoi.map(r=>r['Цех']))].filter(Boolean);$('shopFilter').innerHTML='<option value="all">Все</option>'+shops.map(s=>`<option>${s}</option>`).join('');render()}
function filtered(){const from=$('dateFrom').value,to=$('dateTo').value,shift=$('shiftFilter').value,shop=$('shopFilter').value;state.filteredP=state.prostoi.filter(r=>(!from||r['Дата']>=from)&&(!to||r['Дата']<=to)&&(shift==='all'||r['Смена_название']===shift)&&(shop==='all'||r['Цех']===shop));state.filteredB=state.brak.filter(r=>(!from||r['Дата контроля']>=from)&&(!to||r['Дата контроля']<=to)&&(shift==='all'||r['Смена (название)']===shift))}
function group(rows,key,val){return rows.reduce((a,r)=>{const k=r[key]||'Не указано';a[k]=(a[k]||0)+val(r);return a},{})}
function topEntry(obj){return Object.entries(obj).sort((a,b)=>b[1]-a[1])[0]||['—',0]}
function moneyLossByOperation(){const p=group(state.filteredP.filter(r=>r['Плановый простой']!=='да'),'Операция',r=>num(r['Длительность, мин'])/60*2800);const b=group(state.filteredB,'Операция-источник',r=>num(r['Кол-во, шт'])*450);return [...new Set([...Object.keys(p),...Object.keys(b)])].reduce((a,k)=>(a[k]=(p[k]||0)+(b[k]||0),a),{})}
function render(){filtered();renderKpi();drawCharts();renderTables()}
function renderKpi(){const unplanned=state.filteredP.filter(r=>r['Плановый простой']!=='да');const hours=unplanned.reduce((s,r)=>s+num(r['Длительность, мин'])/60,0);const defects=state.filteredB.reduce((s,r)=>s+num(r['Кол-во, шт']),0);const risk=topEntry(moneyLossByOperation());$('kpiHours').textContent=hours.toFixed(1);$('kpiDefects').textContent=defects.toLocaleString('ru-RU');$('kpiOutput').textContent=Math.max(0,Math.round(PLANNED_OUTPUT_DETAILS-defects)).toLocaleString('ru-RU');$('kpiRisk').textContent=risk[0];const reason=topEntry(group(unplanned,'Причина простоя',r=>num(r['Длительность, мин'])/60));const defectShift=topEntry(group(state.filteredB,'Смена (название)',r=>num(r['Кол-во, шт'])));$('summaryInsight').innerHTML=`<b>Вывод для директора:</b> главная денежная зона риска — <b>${risk[0]}</b> (≈${Math.round(risk[1]).toLocaleString('ru-RU')} ₽ условных потерь). Самая дорогая причина простоя: <b>${reason[0]}</b> (${reason[1].toFixed(1)} ч). Брак чаще фиксируется в смену <b>${defectShift[0]}</b> (${defectShift[1]} шт.). Условная выработка считается как план ${PLANNED_OUTPUT_DETAILS.toLocaleString('ru-RU')} деталей минус детали, забракованные ОТК.`;$('downtimeInsight').innerHTML=`Сначала разбирать причину <b>${reason[0]}</b>: она даёт максимум неплановых часов и должна попасть в план действий мастера смены.`;const op=topEntry(group(state.filteredB,'Операция-источник',r=>num(r['Кол-во, шт'])));$('defectInsight').innerHTML=`Фокус ОТК: операция <b>${op[0]}</b> даёт максимум брака (${op[1]} шт.). Сравните её по сменам и датам на графике слева.`}
function chart(id,type,labels,datasets,opts={}){state.charts[id]?.destroy();state.charts[id]=new Chart($(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},...opts}})}
function drawCharts(){const unplanned=state.filteredP.filter(r=>r['Плановый простой']!=='да');let g=group(unplanned,'Операция',r=>num(r['Длительность, мин'])/60);chart('lossByOperation','bar',Object.keys(g),[{label:'часы',data:Object.values(g),backgroundColor:'#9b4a22'}]);g=moneyLossByOperation();chart('moneyMap','bar',Object.keys(g),[{label:'условные потери, ₽',data:Object.values(g),backgroundColor:'#264f45'}]);g=group(unplanned,'Причина простоя',r=>num(r['Длительность, мин'])/60);const sorted=Object.entries(g).sort((a,b)=>b[1]-a[1]);chart('paretoReasons','bar',sorted.map(x=>x[0]),[{label:'часы',data:sorted.map(x=>x[1]),backgroundColor:'#b9362b'}]);g=group(unplanned,'Станок',r=>num(r['Длительность, мин'])/60);chart('machinesDowntime','bar',Object.keys(g),[{label:'часы',data:Object.values(g),backgroundColor:'#c9843d'}]);const dates=[...new Set(state.filteredB.map(r=>r['Дата контроля']))].sort(),shifts=['День','Ночь'];chart('defectTrend','line',dates,shifts.map((s,i)=>({label:s,data:dates.map(d=>state.filteredB.filter(r=>r['Дата контроля']===d&&r['Смена (название)']===s).reduce((a,r)=>a+num(r['Кол-во, шт']),0)),borderColor:i?'#b9362b':'#264f45',tension:.25})));g=group(state.filteredB,'Операция-источник',r=>num(r['Кол-во, шт']));chart('defectByOperation','doughnut',Object.keys(g),[{label:'шт',data:Object.values(g),backgroundColor:['#264f45','#9b4a22','#c9843d','#b9362b','#766a5d']}])}
function renderTables(){renderTable('prostoiTable',state.filteredP);renderTable('brakTable',state.filteredB)}
function renderTable(id,rows){const q=norm($('search').value).toLowerCase();const data=rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)).slice(0,300);if(!data.length){$(id).innerHTML='<tr><td>Нет данных</td></tr>';return}const keys=Object.keys(data[0]);$(id).innerHTML='<thead><tr>'+keys.map(k=>`<th>${k}</th>`).join('')+'</tr></thead><tbody>'+data.map(r=>'<tr>'+keys.map(k=>`<td>${r[k]}</td>`).join('')+'</tr>').join('')+'</tbody>';$(id).querySelectorAll('th').forEach((th,i)=>th.onclick=()=>{rows.sort((a,b)=>String(a[keys[i]]).localeCompare(String(b[keys[i]]),'ru',{numeric:true}));renderTable(id,rows)})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.sheet').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});document.querySelectorAll('.pdf').forEach(b=>b.onclick=()=>html2pdf().from(b.parentElement).set({filename:`${b.parentElement.id}.pdf`,margin:8,html2canvas:{scale:2}}).save());$('loadBtn').onclick=loadUser;$('applyFilters').onclick=render;$('search').oninput=renderTables;loadDefaults().catch(e=>{$('loadStatus').textContent='Откройте через локальный сервер и/или загрузите файлы кнопкой';console.error(e)});
